AllCops:
  Exclude:
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'script/**/*'
    - 'lib/mina/**/*'
    - 'lib/tasks/**/*'
    - 'config/**/*'
    - 'Guardfile'
    - 'Gemfile'
    - 'Rakefile'
  TargetRubyVersion: 2.3
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 30
Metrics/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 200
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/IndentArray:
  EnforcedStyle: consistent
Style/ClosingParenthesisIndentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

