AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'lib/mina/**/*'
    - 'lib/tasks/**/*'
    - 'config/**/*'
    - 'Guardfile'
  TargetRubyVersion: 2.2
Documentation:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Metrics/ClassLength:
  Max: 250
Metrics/ModuleLength:
  Max: 250
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/IndentArray:
  EnforcedStyle: consistent
Style/ClosingParenthesisIndentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MutableConstant:
  Exclude:
    - 'engines/*/lib/*/version.rb'
