development:
  adapter: postgresql
  database: betafish_development
  encoding: UTF8
  username: betafish
  password: betafish
  port: 5432
  host: localhost
  min_messages: warning
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>

test:
  adapter: postgresql
  database: betafish_test<%= ENV['TEST_ENV_NUMBER'] %>
  encoding: UTF8
  username: betafish
  password: betafish
  port: 5432
  host: localhost
  min_messages: warning

staging:
  adapter: postgresql
  database: betafish_staging
  encoding: UTF8
  username: betafish
  password: betafish
  port: 5432
  host: localhost
  min_messages: warning
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>

production:
  adapter: postgresql
  database: betafish_production
  encoding: UTF8
  username: betafish
  password: betafish
  port: 5432
  host: localhost
  min_messages: warning
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
